name: janus-videoroom-streamer
base: core20
summary: Janus Videoroom streamer
adopt-info: streamer
description: |
  Intended to help restream from any source supported by GStreamer to Janus Videoroom.
license: GPL-3.0
grade: devel
confinement: strict

architectures:
  - build-on: amd64
#  - build-on: i386
  - build-on: armhf

environment:
  GST_DEBUG: 3
  GST_DEBUG_NO_COLOR: 1
  GST_PLUGIN_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gstreamer-1.0
  GST_PLUGIN_SYSTEM_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gstreamer-1.0
  GST_PLUGIN_SCANNER: $SNAP/usr/libexec/$SNAPCRAFT_ARCH_TRIPLET/gstreamer-1.0/gst-plugin-scanner
  LD_LIBRARY_PATH: $SNAP/opt/${SNAP_NAME}/lib

layout:
  /opt/janus-videoroom-streamer/lib:
    symlink: $SNAP/opt/janus-videoroom-streamer/lib

parts:
  lws:
    plugin: cmake
    source-type: git
    source: https://github.com/warmcat/libwebsockets.git
    source-branch: v4.1-stable
    cmake-parameters:
      - -DLWS_WITHOUT_TESTAPPS=ON
      - -DLWS_WITH_GLIB=ON
      - -DCMAKE_INSTALL_PREFIX=/opt/${SNAPCRAFT_PROJECT_NAME}
    build-packages:
      - libssl-dev
      - libglib2.0-dev
    stage-packages:
      - libssl1.1

  gstreamer:
    plugin: meson
    source-type: git
    source: https://github.com/GStreamer/gst-build.git
    source-tag: 1.18.3
    meson-parameters:
      - --prefix=/usr
      - -Dbase=enabled
      - -Dgood=enabled
      - -Dbad=enabled
      - -Dugly=enabled
      - -Ddevtools=disabled
      - -Ddoc=disabled
      - -Dexamples=disabled
      - -Dges=disabled
      - -Dgst-examples=disabled
      - -Dgtk_doc=disabled
      - -Dlibav=enabled
      - -Dlibnice=enabled
      - -Dnls=disabled
      - -Domx=disabled
      - -Dpython=disabled
      - -Dqt5=disabled
      - -Drs=disabled
      - -Drtsp_server=disabled
      - -Dsharp=disabled
      - -Dtests=disabled
      - -Dtls=enabled
      - -Dvaapi=disabled
    build-packages:
      - flex
      - bison
      - nasm
      - libvpx-dev
      - libsrtp2-dev
      - libmount-dev
    stage-packages:
      - libvpx6
      - libsrtp2-1

  streamer:
    plugin: cmake
    source-type: git
    source: https://github.com/WebRTSP/JanusVideoroomStreamer.git
    build-environment:
      - PKG_CONFIG_PATH: $SNAPCRAFT_STAGE/opt/${SNAPCRAFT_PROJECT_NAME}/lib/pkgconfig:$PKG_CONFIG_PATH
    override-pull: |
        snapcraftctl pull
        snapcraftctl set-version "$(git describe --always)"
    after:
      - lws
      - gstreamer
    build-packages:
      - pkg-config
      - g++
      - make
      - libspdlog-dev
      - libconfig-dev
    stage-packages:
      - libconfig9
      - libjansson4
      - libslang2
      - libgpm2
      - libpulse0
      - libx264-155

apps:
  JanusVideoroomStreamer:
    command: usr/local/bin/JanusVideoroomStreamer
    daemon: simple
    plugs:
      - network
